//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Option: light framework (CF/Silverlight) enabled
    
// Generated from: proto/common.proto
namespace qp_server
{
  [global::ProtoBuf.ProtoContract(Name=@"qp_packet")]
  public partial class qp_packet : global::ProtoBuf.IExtensible
  {
    public qp_packet() {}
    
    private int _cmd;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private byte[] _serialized;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"serialized", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] serialized
    {
      get { return _serialized?? null; }
      set { _serialized = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool serializedSpecified
    {
      get { return this._serialized != null; }
      set { if (value == (this._serialized== null)) this._serialized = value ? this.serialized : (byte[])null; }
    }
    private bool ShouldSerializeserialized() { return serializedSpecified; }
    private void Resetserialized() { serializedSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"qp_login_req")]
  public partial class qp_login_req : global::ProtoBuf.IExtensible
  {
    public qp_login_req() {}
    
    private string _account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _pwd;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"pwd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string pwd
    {
      get { return _pwd; }
      set { _pwd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"pb_user_public_data")]
  public partial class pb_user_public_data : global::ProtoBuf.IExtensible
  {
    public pb_user_public_data() {}
    
    private int _user_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private string _avatar_url;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"avatar_url", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string avatar_url
    {
      get { return _avatar_url; }
      set { _avatar_url = value; }
    }
    private string _nick_name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"nick_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nick_name
    {
      get { return _nick_name; }
      set { _nick_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"pb_user_private_data")]
  public partial class pb_user_private_data : global::ProtoBuf.IExtensible
  {
    public pb_user_private_data() {}
    
    private int _room_card_count;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"room_card_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int room_card_count
    {
      get { return _room_card_count; }
      set { _room_card_count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"qp_login_rsp")]
  public partial class qp_login_rsp : global::ProtoBuf.IExtensible
  {
    public qp_login_rsp() {}
    
    private int _state;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    private qp_server.pb_user_public_data _public_data = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"public_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public qp_server.pb_user_public_data public_data
    {
      get { return _public_data; }
      set { _public_data = value; }
    }
    private qp_server.pb_user_private_data _private_data = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"private_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public qp_server.pb_user_private_data private_data
    {
      get { return _private_data; }
      set { _private_data = value; }
    }
    private qp_server.pb_room_data _room_data = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"room_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public qp_server.pb_room_data room_data
    {
      get { return _room_data; }
      set { _room_data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"pb_room_cfg")]
  public partial class pb_room_cfg : global::ProtoBuf.IExtensible
  {
    public pb_room_cfg() {}
    
    private string _room_name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"room_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string room_name
    {
      get { return _room_name; }
      set { _room_name = value; }
    }
    private bool _is_aa;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"is_aa", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_aa
    {
      get { return _is_aa; }
      set { _is_aa = value; }
    }
    private int _double_down_score;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"double_down_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int double_down_score
    {
      get { return _double_down_score; }
      set { _double_down_score = value; }
    }
    private bool _is_laizi_playmethod;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"is_laizi_playmethod", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_laizi_playmethod
    {
      get { return _is_laizi_playmethod; }
      set { _is_laizi_playmethod = value; }
    }
    private bool _is_ob;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"is_ob", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_ob
    {
      get { return _is_ob; }
      set { _is_ob = value; }
    }
    private bool _is_random;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"is_random", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_random
    {
      get { return _is_random; }
      set { _is_random = value; }
    }
    private bool _is_not_voice;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"is_not_voice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_not_voice
    {
      get { return _is_not_voice; }
      set { _is_not_voice = value; }
    }
    private bool _is_safe_mode;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"is_safe_mode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_safe_mode
    {
      get { return _is_safe_mode; }
      set { _is_safe_mode = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _lock_userid_list = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(9, Name=@"lock_userid_list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> lock_userid_list
    {
      get { return _lock_userid_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"qp_create_room_req")]
  public partial class qp_create_room_req : global::ProtoBuf.IExtensible
  {
    public qp_create_room_req() {}
    
    private qp_server.pb_room_cfg _cfg;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cfg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public qp_server.pb_room_cfg cfg
    {
      get { return _cfg; }
      set { _cfg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"qp_create_room_rsp")]
  public partial class qp_create_room_rsp : global::ProtoBuf.IExtensible
  {
    public qp_create_room_rsp() {}
    
    private int _state;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    private int? _room_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"room_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int room_id
    {
      get { return _room_id?? default(int); }
      set { _room_id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool room_idSpecified
    {
      get { return this._room_id != null; }
      set { if (value == (this._room_id== null)) this._room_id = value ? this.room_id : (int?)null; }
    }
    private bool ShouldSerializeroom_id() { return room_idSpecified; }
    private void Resetroom_id() { room_idSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"qp_join_room_req")]
  public partial class qp_join_room_req : global::ProtoBuf.IExtensible
  {
    public qp_join_room_req() {}
    
    private int _room_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"room_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int room_id
    {
      get { return _room_id; }
      set { _room_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"pb_room_data")]
  public partial class pb_room_data : global::ProtoBuf.IExtensible
  {
    public pb_room_data() {}
    
    private int _room_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"room_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int room_id
    {
      get { return _room_id; }
      set { _room_id = value; }
    }
    private qp_server.pb_room_cfg _cfg;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"cfg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public qp_server.pb_room_cfg cfg
    {
      get { return _cfg; }
      set { _cfg = value; }
    }
    private readonly global::System.Collections.Generic.List<qp_server.pb_room_user> _room_users = new global::System.Collections.Generic.List<qp_server.pb_room_user>();
    [global::ProtoBuf.ProtoMember(3, Name=@"room_users", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<qp_server.pb_room_user> room_users
    {
      get { return _room_users; }
    }
  
    private byte[] _game_data;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"game_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] game_data
    {
      get { return _game_data?? null; }
      set { _game_data = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool game_dataSpecified
    {
      get { return this._game_data != null; }
      set { if (value == (this._game_data== null)) this._game_data = value ? this.game_data : (byte[])null; }
    }
    private bool ShouldSerializegame_data() { return game_dataSpecified; }
    private void Resetgame_data() { game_dataSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"pb_room_user")]
  public partial class pb_room_user : global::ProtoBuf.IExtensible
  {
    public pb_room_user() {}
    
    private qp_server.pb_user_public_data _user_public_data;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"user_public_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public qp_server.pb_user_public_data user_public_data
    {
      get { return _user_public_data; }
      set { _user_public_data = value; }
    }
    private int _seat_number;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"seat_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int seat_number
    {
      get { return _seat_number; }
      set { _seat_number = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"qp_join_room_rsp")]
  public partial class qp_join_room_rsp : global::ProtoBuf.IExtensible
  {
    public qp_join_room_rsp() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private qp_server.pb_room_data _room_data = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"room_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public qp_server.pb_room_data room_data
    {
      get { return _room_data; }
      set { _room_data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"qp_join_room_push")]
  public partial class qp_join_room_push : global::ProtoBuf.IExtensible
  {
    public qp_join_room_push() {}
    
    private qp_server.pb_user_public_data _public_data;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"public_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public qp_server.pb_user_public_data public_data
    {
      get { return _public_data; }
      set { _public_data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"qp_sitdown_req")]
  public partial class qp_sitdown_req : global::ProtoBuf.IExtensible
  {
    public qp_sitdown_req() {}
    
    private int _seat_num;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seat_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int seat_num
    {
      get { return _seat_num; }
      set { _seat_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"qp_sitdown_rsp")]
  public partial class qp_sitdown_rsp : global::ProtoBuf.IExtensible
  {
    public qp_sitdown_rsp() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int? _seat_num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"seat_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int seat_num
    {
      get { return _seat_num?? default(int); }
      set { _seat_num = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool seat_numSpecified
    {
      get { return this._seat_num != null; }
      set { if (value == (this._seat_num== null)) this._seat_num = value ? this.seat_num : (int?)null; }
    }
    private bool ShouldSerializeseat_num() { return seat_numSpecified; }
    private void Resetseat_num() { seat_numSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"qp_sitdown_push")]
  public partial class qp_sitdown_push : global::ProtoBuf.IExtensible
  {
    public qp_sitdown_push() {}
    
    private int _seat_num;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seat_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int seat_num
    {
      get { return _seat_num; }
      set { _seat_num = value; }
    }
    private int _user_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"qp_standup_req")]
  public partial class qp_standup_req : global::ProtoBuf.IExtensible
  {
    public qp_standup_req() {}
    
    private int? _seat_num;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"seat_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int seat_num
    {
      get { return _seat_num?? default(int); }
      set { _seat_num = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool seat_numSpecified
    {
      get { return this._seat_num != null; }
      set { if (value == (this._seat_num== null)) this._seat_num = value ? this.seat_num : (int?)null; }
    }
    private bool ShouldSerializeseat_num() { return seat_numSpecified; }
    private void Resetseat_num() { seat_numSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"qp_standup_rsp")]
  public partial class qp_standup_rsp : global::ProtoBuf.IExtensible
  {
    public qp_standup_rsp() {}
    
    private int _state;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"qp_standup_push")]
  public partial class qp_standup_push : global::ProtoBuf.IExtensible
  {
    public qp_standup_push() {}
    
    private int _seat_num;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seat_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int seat_num
    {
      get { return _seat_num; }
      set { _seat_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"qp_exit_room_req")]
  public partial class qp_exit_room_req : global::ProtoBuf.IExtensible
  {
    public qp_exit_room_req() {}
    
    private int? _noop;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"noop", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int noop
    {
      get { return _noop?? default(int); }
      set { _noop = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool noopSpecified
    {
      get { return this._noop != null; }
      set { if (value == (this._noop== null)) this._noop = value ? this.noop : (int?)null; }
    }
    private bool ShouldSerializenoop() { return noopSpecified; }
    private void Resetnoop() { noopSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"qp_exit_room_rsp")]
  public partial class qp_exit_room_rsp : global::ProtoBuf.IExtensible
  {
    public qp_exit_room_rsp() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"qp_exit_room_push")]
  public partial class qp_exit_room_push : global::ProtoBuf.IExtensible
  {
    public qp_exit_room_push() {}
    
    private int _user_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"qp_game_data")]
  public partial class qp_game_data : global::ProtoBuf.IExtensible
  {
    public qp_game_data() {}
    
    private byte[] _game_data;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"game_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] game_data
    {
      get { return _game_data; }
      set { _game_data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"qp_ping_req")]
  public partial class qp_ping_req : global::ProtoBuf.IExtensible
  {
    public qp_ping_req() {}
    
    private int? _noop;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"noop", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int noop
    {
      get { return _noop?? default(int); }
      set { _noop = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool noopSpecified
    {
      get { return this._noop != null; }
      set { if (value == (this._noop== null)) this._noop = value ? this.noop : (int?)null; }
    }
    private bool ShouldSerializenoop() { return noopSpecified; }
    private void Resetnoop() { noopSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"qp_ping_rsp")]
  public partial class qp_ping_rsp : global::ProtoBuf.IExtensible
  {
    public qp_ping_rsp() {}
    
    private int? _noop;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"noop", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int noop
    {
      get { return _noop?? default(int); }
      set { _noop = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool noopSpecified
    {
      get { return this._noop != null; }
      set { if (value == (this._noop== null)) this._noop = value ? this.noop : (int?)null; }
    }
    private bool ShouldSerializenoop() { return noopSpecified; }
    private void Resetnoop() { noopSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ws_cmd")]
    public enum ws_cmd
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_QP_LOGIN_REQ", Value=1001)]
      CMD_QP_LOGIN_REQ = 1001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_QP_LOGIN_RSP", Value=1002)]
      CMD_QP_LOGIN_RSP = 1002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_QP_CREATE_ROOM_REQ", Value=1003)]
      CMD_QP_CREATE_ROOM_REQ = 1003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_QP_CREATE_ROOM_RSP", Value=1004)]
      CMD_QP_CREATE_ROOM_RSP = 1004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_QP_JOIN_ROOM_REQ", Value=1005)]
      CMD_QP_JOIN_ROOM_REQ = 1005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_QP_JOIN_ROOM_RSP", Value=1006)]
      CMD_QP_JOIN_ROOM_RSP = 1006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_QP_JOIN_ROOM_PUSH", Value=1007)]
      CMD_QP_JOIN_ROOM_PUSH = 1007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_QP_SITDOWN_REQ", Value=1008)]
      CMD_QP_SITDOWN_REQ = 1008,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_QP_SITDOWN_RSP", Value=1009)]
      CMD_QP_SITDOWN_RSP = 1009,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_QP_SITDOWN_PUSH", Value=1010)]
      CMD_QP_SITDOWN_PUSH = 1010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_QP_STANDUP_REQ", Value=1011)]
      CMD_QP_STANDUP_REQ = 1011,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_QP_STANDUP_RSP", Value=1012)]
      CMD_QP_STANDUP_RSP = 1012,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_QP_STANDUP_PUSH", Value=1013)]
      CMD_QP_STANDUP_PUSH = 1013,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_QP_EXIT_ROOM_REQ", Value=1014)]
      CMD_QP_EXIT_ROOM_REQ = 1014,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_QP_EXIT_ROOM_RSP", Value=1015)]
      CMD_QP_EXIT_ROOM_RSP = 1015,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_QP_EXIT_ROOM_PUSH", Value=1016)]
      CMD_QP_EXIT_ROOM_PUSH = 1016,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_QP_GAME_DATA", Value=2001)]
      CMD_QP_GAME_DATA = 2001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_QP_PING_REQ", Value=5001)]
      CMD_QP_PING_REQ = 5001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_QP_PING_RSP", Value=5002)]
      CMD_QP_PING_RSP = 5002
    }
  
}