//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Option: light framework (CF/Silverlight) enabled
    
// Generated from: proto/ss510k.proto
namespace qp_mj
{
  [global::ProtoBuf.ProtoContract(Name=@"qp_logic")]
  public partial class qp_logic : global::ProtoBuf.IExtensible
  {
    public qp_logic() {}
    
    private int _cmd;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private byte[] _serialized;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"serialized", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] serialized
    {
      get { return _serialized?? null; }
      set { _serialized = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool serializedSpecified
    {
      get { return this._serialized != null; }
      set { if (value == (this._serialized== null)) this._serialized = value ? this.serialized : (byte[])null; }
    }
    private bool ShouldSerializeserialized() { return serializedSpecified; }
    private void Resetserialized() { serializedSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"qp_mj_game_start_notify")]
  public partial class qp_mj_game_start_notify : global::ProtoBuf.IExtensible
  {
    public qp_mj_game_start_notify() {}
    
    private readonly global::System.Collections.Generic.List<uint> _pai = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"pai", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> pai
    {
      get { return _pai; }
    }
  
    private int _banker_seat_number;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"banker_seat_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int banker_seat_number
    {
      get { return _banker_seat_number; }
      set { _banker_seat_number = value; }
    }
    private uint? _oper_flag;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"oper_flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint oper_flag
    {
      get { return _oper_flag?? default(uint); }
      set { _oper_flag = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool oper_flagSpecified
    {
      get { return this._oper_flag != null; }
      set { if (value == (this._oper_flag== null)) this._oper_flag = value ? this.oper_flag : (uint?)null; }
    }
    private bool ShouldSerializeoper_flag() { return oper_flagSpecified; }
    private void Resetoper_flag() { oper_flagSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"seat_score_item")]
  public partial class seat_score_item : global::ProtoBuf.IExtensible
  {
    public seat_score_item() {}
    
    private int _seat_number;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seat_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int seat_number
    {
      get { return _seat_number; }
      set { _seat_number = value; }
    }
    private int _score;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"qp_mj_game_end_notify")]
  public partial class qp_mj_game_end_notify : global::ProtoBuf.IExtensible
  {
    public qp_mj_game_end_notify() {}
    
    private uint _end_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"end_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint end_type
    {
      get { return _end_type; }
      set { _end_type = value; }
    }
    private int _hupai_seatnumber;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"hupai_seatnumber", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hupai_seatnumber
    {
      get { return _hupai_seatnumber; }
      set { _hupai_seatnumber = value; }
    }
    private uint _hupai_value;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"hupai_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint hupai_value
    {
      get { return _hupai_value; }
      set { _hupai_value = value; }
    }
    private uint _hupai_type;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"hupai_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint hupai_type
    {
      get { return _hupai_type; }
      set { _hupai_type = value; }
    }
    private int _fangpao_seatnumber;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"fangpao_seatnumber", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fangpao_seatnumber
    {
      get { return _fangpao_seatnumber; }
      set { _fangpao_seatnumber = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _seat0_pai = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(6, Name=@"seat0_pai", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> seat0_pai
    {
      get { return _seat0_pai; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _seat1_pai = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(7, Name=@"seat1_pai", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> seat1_pai
    {
      get { return _seat1_pai; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _seat2_pai = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(8, Name=@"seat2_pai", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> seat2_pai
    {
      get { return _seat2_pai; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _seat3_pai = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(9, Name=@"seat3_pai", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> seat3_pai
    {
      get { return _seat3_pai; }
    }
  
    private readonly global::System.Collections.Generic.List<qp_mj.seat_score_item> _scores = new global::System.Collections.Generic.List<qp_mj.seat_score_item>();
    [global::ProtoBuf.ProtoMember(10, Name=@"scores", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<qp_mj.seat_score_item> scores
    {
      get { return _scores; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"qp_mj_oper_req")]
  public partial class qp_mj_oper_req : global::ProtoBuf.IExtensible
  {
    public qp_mj_oper_req() {}
    
    private uint _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint? _v1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"v1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint v1
    {
      get { return _v1?? default(uint); }
      set { _v1 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool v1Specified
    {
      get { return this._v1 != null; }
      set { if (value == (this._v1== null)) this._v1 = value ? this.v1 : (uint?)null; }
    }
    private bool ShouldSerializev1() { return v1Specified; }
    private void Resetv1() { v1Specified = false; }
    
    private uint? _v2;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"v2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint v2
    {
      get { return _v2?? default(uint); }
      set { _v2 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool v2Specified
    {
      get { return this._v2 != null; }
      set { if (value == (this._v2== null)) this._v2 = value ? this.v2 : (uint?)null; }
    }
    private bool ShouldSerializev2() { return v2Specified; }
    private void Resetv2() { v2Specified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"qp_mj_oper_notify")]
  public partial class qp_mj_oper_notify : global::ProtoBuf.IExtensible
  {
    public qp_mj_oper_notify() {}
    
    private int _seat_numer;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"seat_numer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int seat_numer
    {
      get { return _seat_numer; }
      set { _seat_numer = value; }
    }
    private uint _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint? _v1;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"v1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint v1
    {
      get { return _v1?? default(uint); }
      set { _v1 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool v1Specified
    {
      get { return this._v1 != null; }
      set { if (value == (this._v1== null)) this._v1 = value ? this.v1 : (uint?)null; }
    }
    private bool ShouldSerializev1() { return v1Specified; }
    private void Resetv1() { v1Specified = false; }
    
    private uint? _v2;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"v2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint v2
    {
      get { return _v2?? default(uint); }
      set { _v2 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool v2Specified
    {
      get { return this._v2 != null; }
      set { if (value == (this._v2== null)) this._v2 = value ? this.v2 : (uint?)null; }
    }
    private bool ShouldSerializev2() { return v2Specified; }
    private void Resetv2() { v2Specified = false; }
    
    private int? _v3;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"v3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int v3
    {
      get { return _v3?? default(int); }
      set { _v3 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool v3Specified
    {
      get { return this._v3 != null; }
      set { if (value == (this._v3== null)) this._v3 = value ? this.v3 : (int?)null; }
    }
    private bool ShouldSerializev3() { return v3Specified; }
    private void Resetv3() { v3Specified = false; }
    
    private int? _next_oper_seat_num;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"next_oper_seat_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int next_oper_seat_num
    {
      get { return _next_oper_seat_num?? default(int); }
      set { _next_oper_seat_num = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool next_oper_seat_numSpecified
    {
      get { return this._next_oper_seat_num != null; }
      set { if (value == (this._next_oper_seat_num== null)) this._next_oper_seat_num = value ? this.next_oper_seat_num : (int?)null; }
    }
    private bool ShouldSerializenext_oper_seat_num() { return next_oper_seat_numSpecified; }
    private void Resetnext_oper_seat_num() { next_oper_seat_numSpecified = false; }
    
    private uint? _next_oper_flag;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"next_oper_flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint next_oper_flag
    {
      get { return _next_oper_flag?? default(uint); }
      set { _next_oper_flag = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool next_oper_flagSpecified
    {
      get { return this._next_oper_flag != null; }
      set { if (value == (this._next_oper_flag== null)) this._next_oper_flag = value ? this.next_oper_flag : (uint?)null; }
    }
    private bool ShouldSerializenext_oper_flag() { return next_oper_flagSpecified; }
    private void Resetnext_oper_flag() { next_oper_flagSpecified = false; }
    
    private uint? _next_oper_value1;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"next_oper_value1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint next_oper_value1
    {
      get { return _next_oper_value1?? default(uint); }
      set { _next_oper_value1 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool next_oper_value1Specified
    {
      get { return this._next_oper_value1 != null; }
      set { if (value == (this._next_oper_value1== null)) this._next_oper_value1 = value ? this.next_oper_value1 : (uint?)null; }
    }
    private bool ShouldSerializenext_oper_value1() { return next_oper_value1Specified; }
    private void Resetnext_oper_value1() { next_oper_value1Specified = false; }
    
    private uint? _next_oper_value2;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"next_oper_value2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint next_oper_value2
    {
      get { return _next_oper_value2?? default(uint); }
      set { _next_oper_value2 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool next_oper_value2Specified
    {
      get { return this._next_oper_value2 != null; }
      set { if (value == (this._next_oper_value2== null)) this._next_oper_value2 = value ? this.next_oper_value2 : (uint?)null; }
    }
    private bool ShouldSerializenext_oper_value2() { return next_oper_value2Specified; }
    private void Resetnext_oper_value2() { next_oper_value2Specified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::ProtoBuf.ProtoContract(Name=@"qp_mj_oper_error")]
  public partial class qp_mj_oper_error : global::ProtoBuf.IExtensible
  {
    public qp_mj_oper_error() {}
    
    private uint _error_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"error_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint error_type
    {
      get { return _error_type; }
      set { _error_type = value; }
    }
    private uint? _error_value1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"error_value1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint error_value1
    {
      get { return _error_value1?? default(uint); }
      set { _error_value1 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool error_value1Specified
    {
      get { return this._error_value1 != null; }
      set { if (value == (this._error_value1== null)) this._error_value1 = value ? this.error_value1 : (uint?)null; }
    }
    private bool ShouldSerializeerror_value1() { return error_value1Specified; }
    private void Reseterror_value1() { error_value1Specified = false; }
    
    private uint? _error_value2;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"error_value2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint error_value2
    {
      get { return _error_value2?? default(uint); }
      set { _error_value2 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool error_value2Specified
    {
      get { return this._error_value2 != null; }
      set { if (value == (this._error_value2== null)) this._error_value2 = value ? this.error_value2 : (uint?)null; }
    }
    private bool ShouldSerializeerror_value2() { return error_value2Specified; }
    private void Reseterror_value2() { error_value2Specified = false; }
    
    private uint? _oper_flag;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"oper_flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint oper_flag
    {
      get { return _oper_flag?? default(uint); }
      set { _oper_flag = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool oper_flagSpecified
    {
      get { return this._oper_flag != null; }
      set { if (value == (this._oper_flag== null)) this._oper_flag = value ? this.oper_flag : (uint?)null; }
    }
    private bool ShouldSerializeoper_flag() { return oper_flagSpecified; }
    private void Resetoper_flag() { oper_flagSpecified = false; }
    
    private uint? _oper_value1;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"oper_value1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint oper_value1
    {
      get { return _oper_value1?? default(uint); }
      set { _oper_value1 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool oper_value1Specified
    {
      get { return this._oper_value1 != null; }
      set { if (value == (this._oper_value1== null)) this._oper_value1 = value ? this.oper_value1 : (uint?)null; }
    }
    private bool ShouldSerializeoper_value1() { return oper_value1Specified; }
    private void Resetoper_value1() { oper_value1Specified = false; }
    
    private uint? _oper_value2;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"oper_value2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint oper_value2
    {
      get { return _oper_value2?? default(uint); }
      set { _oper_value2 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    
    public bool oper_value2Specified
    {
      get { return this._oper_value2 != null; }
      set { if (value == (this._oper_value2== null)) this._oper_value2 = value ? this.oper_value2 : (uint?)null; }
    }
    private bool ShouldSerializeoper_value2() { return oper_value2Specified; }
    private void Resetoper_value2() { oper_value2Specified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ws_cmd")]
    public enum ws_cmd
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_MJ_GAME_START_NOTIFY", Value=10001)]
      CMD_MJ_GAME_START_NOTIFY = 10001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_MJ_GAME_END_NOTIFY", Value=10002)]
      CMD_MJ_GAME_END_NOTIFY = 10002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_MJ_OPER_REQ", Value=10003)]
      CMD_MJ_OPER_REQ = 10003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_MJ_OPER_NOTIFY", Value=10004)]
      CMD_MJ_OPER_NOTIFY = 10004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CMD_MJ_OPER_ERROR", Value=10005)]
      CMD_MJ_OPER_ERROR = 10005
    }
  
}